# Generated by Django 3.2.9 on 2021-11-27 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import json.decoder
import json.encoder
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataSet', '0002_auto_20211128_0202'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateSharingModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enc_data', models.BinaryField(max_length=2000, null=True)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting for other party'), ('STARTED', 'PSI started'), ('FINISHED', 'PSI Finished'), ('ABORTED', 'PSI Session Aborted')], default='WAITING', max_length=10)),
                ('res', models.JSONField(decoder=json.decoder.JSONDecoder, encoder=json.encoder.JSONEncoder, null=True)),
                ('client1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_id1', to=settings.AUTH_USER_MODEL)),
                ('client2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_id2', to=settings.AUTH_USER_MODEL)),
                ('data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='dataSet.datasetmodel')),
            ],
        ),
    ]
