# Generated by Django 3.2.9 on 2021-11-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privateSharing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatesharingmodel',
            name='enc_data',
            field=models.BinaryField(editable=True, max_length=2000, null=True),
        ),
    ]
